apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "iam.gke.io/gcp-service-account": {{ .Chart.Name }}@{{ .Values.google.projectId }}.iam.gserviceaccount.com
